In [1]:
import numpy as np
import pandas as pd

file_path = "train.csv"
dataframe = pd.read_csv(file_path, sep=';')
dataframe

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2181,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2182,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2183,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2184,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2185,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df_out_label = dataframe.drop(columns="label")
df_out_label

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2181,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2182,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2183,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2184,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2185,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
matriz_pixel = df_out_label.to_numpy()
matriz_pixel

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [11]:
medias = []
for i in range(len(matriz_pixel)):
    soma = sum(matriz_pixel[i])
    media_pixel = soma/255
    medias.append(media_pixel)
#print(medias)
mediasdf = pd.DataFrame({'intensidade': medias})
mediasdf

      intensidade
0      145.435294
1      118.576471
2      127.600000
3      138.047059
4      146.215686
...           ...
2181   105.686275
2182   113.050980
2183   110.725490
2184    99.305882
2185   101.172549

[2186 rows x 1 columns]

In [14]:
vetorP = pd.concat([dataframe["label"], mediasdf], axis=1)
vetorP

      label  intensidade
0         0   145.435294
1         0   118.576471
2         0   127.600000
3         0   138.047059
4         0   146.215686
...     ...          ...
2181      5   105.686275
2182      5   113.050980
2183      5   110.725490
2184      5    99.305882
2185      5   101.172549

[2186 rows x 2 columns]